name: Build iOS Dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Compile dylib
        run: |
          clang -arch arm64 -dynamiclib -o modmenu.dylib modmenu.m \
            -framework UIKit -framework Foundation -fobjc-arc -O2
          file modmenu.dylib
      - uses: actions/upload-artifact@v3
        with:
          name: modmenu
          path: modmenu.dylib
